<?php

namespace Database\Seeders;

use App\Models\WebsiteContent;
use Illuminate\Database\Seeder;

class WebsiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds with exact website homepage content.
     */
    public function run(): void
    {
        $contents = [
            // ==========================================
            // 1. HOMEPAGE CONTENT (100% Website Aligned)
            // ==========================================

            // 1.1 Hero Section
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'badge',
                'value' => 'CONSTRUCTION & DEVELOPMENT',
                'type' => 'text',
                'label' => 'Hero Eyebrow / Badge',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'headline',
                'value' => 'Construction, from planning to completion.',
                'type' => 'text',
                'label' => 'Hero Main Heading',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'subheadline',
                'value' => 'Projects delivered with careful planning, clear coordination and attention to detail.',
                'type' => 'textarea',
                'label' => 'Hero Subheadline / Paragraph',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'primary_btn_text',
                'value' => 'View Projects',
                'type' => 'text',
                'label' => 'Primary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'primary_btn_url',
                'value' => '#projects',
                'type' => 'url',
                'label' => 'Primary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'secondary_btn_text',
                'value' => 'Contact Us',
                'type' => 'text',
                'label' => 'Secondary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'secondary_btn_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'Secondary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'stat_number',
                'value' => '24k+',
                'type' => 'text',
                'label' => 'Hero Floating Stat Number',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'stat_label',
                'value' => 'Project Success',
                'type' => 'text',
                'label' => 'Hero Floating Stat Label',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'stamp_text',
                'value' => '• EXPLORE WORK • VIEW PROJECTS',
                'type' => 'text',
                'label' => 'Hero Circular Rotating Stamp Text',
            ],

            // 1.2 About Section
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'badge',
                'value' => 'ABOUT CONSTRUCTION',
                'type' => 'text',
                'label' => 'About Section Badge',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'title',
                'value' => 'Construction built around precision, planning & detail.',
                'type' => 'text',
                'label' => 'About Heading Title',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'highlight_word',
                'value' => 'precision,',
                'type' => 'text',
                'label' => 'Highlighted Sketch Word',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'description',
                'value' => 'We approach every project with careful planning, coordinated execution and close attention to the details that shape the finished work.',
                'type' => 'textarea',
                'label' => 'About Lead Description',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'btn_text',
                'value' => 'DISCOVER MORE',
                'type' => 'text',
                'label' => 'About Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'btn_url',
                'value' => '#projects',
                'type' => 'url',
                'label' => 'About Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_years',
                'value' => '12',
                'type' => 'text',
                'label' => 'Experience Years Number',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Experience Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_title',
                'value' => 'Years of',
                'type' => 'text',
                'label' => 'Experience Title Line',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_subtitle',
                'value' => 'Experience.',
                'type' => 'text',
                'label' => 'Experience Subtitle Line',
            ],

            // 1.3 Features / Interior Execution
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'badge',
                'value' => 'Interior Execution',
                'type' => 'text',
                'label' => 'Features Badge',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'title',
                'value' => 'Interior Work, From Plan To Finish',
                'type' => 'text',
                'label' => 'Features Heading Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'quote',
                'value' => '“Coordinated drywall framing, MEP routing & architectural finishes delivered to spec.”',
                'type' => 'textarea',
                'label' => 'CEO Floating Quote',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'author_name',
                'value' => 'Alexander Joseph Reed',
                'type' => 'text',
                'label' => 'Author Name',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'author_title',
                'value' => 'Founder & CEO',
                'type' => 'text',
                'label' => 'Author Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_1_title',
                'value' => 'Structural Accuracy & Detailing',
                'type' => 'text',
                'label' => 'Feature 1 Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_1_desc',
                'value' => 'Detailed shop drawings and rebar schedules for clean on-site fabrication.',
                'type' => 'textarea',
                'label' => 'Feature 1 Description',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_2_title',
                'value' => 'Spatial & MEP Coordination',
                'type' => 'text',
                'label' => 'Feature 2 Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_2_desc',
                'value' => 'Clash-free routing between structural reinforced concrete and mechanical runs.',
                'type' => 'textarea',
                'label' => 'Feature 2 Description',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_3_title',
                'value' => 'Modular Prefabrication',
                'type' => 'text',
                'label' => 'Feature 3 Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_3_desc',
                'value' => 'Pre-assembled steel sections reducing active crane time and floor cycles.',
                'type' => 'textarea',
                'label' => 'Feature 3 Description',
            ],

            // 1.4 Experience & Results Section
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'badge',
                'value' => 'Project Track Record',
                'type' => 'text',
                'label' => 'Track Record Badge',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'title',
                'value' => 'Planned Work. Controlled Execution.',
                'type' => 'text',
                'label' => 'Section Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'description',
                'value' => 'We coordinate heavy equipment, civil trades, and structural crews to maintain strict schedule milestones from initial ground prep to final building handover.',
                'type' => 'textarea',
                'label' => 'Lead Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'primary_btn_text',
                'value' => 'DISCUSS A PROJECT',
                'type' => 'text',
                'label' => 'Primary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'primary_btn_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'Primary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'secondary_btn_text',
                'value' => 'VIEW RECENT SITES',
                'type' => 'text',
                'label' => 'Secondary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'secondary_btn_url',
                'value' => '#projects',
                'type' => 'url',
                'label' => 'Secondary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_count',
                'value' => '240',
                'type' => 'text',
                'label' => 'Metric 1 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Metric 1 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_title',
                'value' => 'Commercial Builds',
                'type' => 'text',
                'label' => 'Metric 1 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_desc',
                'value' => 'Delivered under direct site supervision.',
                'type' => 'text',
                'label' => 'Metric 1 Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_count',
                'value' => '99',
                'type' => 'text',
                'label' => 'Metric 2 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_suffix',
                'value' => '%',
                'type' => 'text',
                'label' => 'Metric 2 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_title',
                'value' => 'Milestone Compliance',
                'type' => 'text',
                'label' => 'Metric 2 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_desc',
                'value' => 'On-schedule stage completions & handovers.',
                'type' => 'text',
                'label' => 'Metric 2 Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_count',
                'value' => '12',
                'type' => 'text',
                'label' => 'Metric 3 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Metric 3 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_title',
                'value' => 'Years In Field',
                'type' => 'text',
                'label' => 'Metric 3 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_desc',
                'value' => 'Continuous active contractor operations.',
                'type' => 'text',
                'label' => 'Metric 3 Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_count',
                'value' => '180',
                'type' => 'text',
                'label' => 'Metric 4 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Metric 4 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_title',
                'value' => 'Trade Specialists',
                'type' => 'text',
                'label' => 'Metric 4 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_desc',
                'value' => 'Certified steel erectors, formworkers & operators.',
                'type' => 'text',
                'label' => 'Metric 4 Description',
            ],

            // 1.5 Services Section Header
            [
                'page' => 'home',
                'section' => 'services',
                'key' => 'badge',
                'value' => 'CORE CAPABILITIES',
                'type' => 'text',
                'label' => 'Services Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'services',
                'key' => 'title',
                'value' => 'Structured Scopes. Direct Site Execution.',
                'type' => 'text',
                'label' => 'Services Headline',
            ],
            [
                'page' => 'home',
                'section' => 'services',
                'key' => 'subtitle',
                'value' => 'Clear project scopes, realistic floor cycle timelines, and full-time site superintendence for commercial and structural projects.',
                'type' => 'textarea',
                'label' => 'Services Lead Description',
            ],

            // 1.6 Projects Section Header
            [
                'page' => 'home',
                'section' => 'projects',
                'key' => 'badge',
                'value' => 'RECENT PROJECTS',
                'type' => 'text',
                'label' => 'Projects Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'projects',
                'key' => 'title',
                'value' => 'Featured Engineering & Construction Work',
                'type' => 'text',
                'label' => 'Projects Headline',
            ],
            [
                'page' => 'home',
                'section' => 'projects',
                'key' => 'subtitle',
                'value' => 'Explore our signature portfolio of commercial towers, industrial logistics facilities, civic architecture, and civil infrastructure.',
                'type' => 'textarea',
                'label' => 'Projects Lead Description',
            ],

            // 1.7 Testimonials Header & Metrics
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'watermark',
                'value' => 'FEEDBACK',
                'type' => 'text',
                'label' => 'Testimonials Watermark',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'eyebrow',
                'value' => 'Client Feedback',
                'type' => 'text',
                'label' => 'Testimonials Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'title',
                'value' => 'Direct Feedback From <br> Project <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Owners</span> &amp; Developers',
                'type' => 'textarea',
                'label' => 'Testimonials Headline',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'stat_count',
                'value' => '12',
                'type' => 'text',
                'label' => 'Testimonials Metric Count',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'stat_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Testimonials Metric Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'stat_desc',
                'value' => 'Years of repeat commercial developer partnerships and general contracting delivery.',
                'type' => 'textarea',
                'label' => 'Testimonials Metric Description',
            ],

            // 1.8 Why Choose Us Section
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'watermark',
                'value' => 'EXPERTISE',
                'type' => 'text',
                'label' => 'Why Choose Us Watermark',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'badge',
                'value' => 'Our Approach',
                'type' => 'text',
                'label' => 'Why Choose Us Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'title_prefix',
                'value' => 'Practical Construction,',
                'type' => 'text',
                'label' => 'Title Prefix',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'highlight_word',
                'value' => 'Carefully',
                'type' => 'text',
                'label' => 'Title Highlighted Word',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'title_suffix',
                'value' => 'Delivered',
                'type' => 'text',
                'label' => 'Title Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'description',
                'value' => 'We manage builds through accurate material planning, direct trade superintendence, and clear milestone reporting from groundbreaking to project closeout.',
                'type' => 'textarea',
                'label' => 'Why Choose Us Lead Description',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'stat_count',
                'value' => '22',
                'type' => 'text',
                'label' => 'Completed Builds Stat Number',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'stat_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Completed Builds Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'stat_label',
                'value' => 'Completed Builds',
                'type' => 'text',
                'label' => 'Completed Builds Label',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_1_title',
                'value' => 'Tested Materials & Sourcing',
                'type' => 'text',
                'label' => 'Feature 1 Title',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_1_desc',
                'value' => 'Certified grade structural steel, batch-tested concrete, and verified supplier supply chains.',
                'type' => 'textarea',
                'label' => 'Feature 1 Description',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_2_title',
                'value' => 'On-Site Superintendent Control',
                'type' => 'text',
                'label' => 'Feature 2 Title',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_2_desc',
                'value' => 'Full-time field engineers reviewing structural tolerances, subcontractor safety, and daily QA logs.',
                'type' => 'textarea',
                'label' => 'Feature 2 Description',
            ],

            // 1.9 News & Field Logs Header
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'watermark',
                'value' => 'UPDATES',
                'type' => 'text',
                'label' => 'News Section Watermark',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'eyebrow',
                'value' => 'Field Logs & Updates',
                'type' => 'text',
                'label' => 'News Section Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'title',
                'value' => 'Jobsite Notes, Methods &amp; <br> <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Field</span> Updates',
                'type' => 'textarea',
                'label' => 'News Section Title',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'button_text',
                'value' => 'All Field Notes',
                'type' => 'text',
                'label' => 'All Field Notes Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'button_url',
                'value' => '#news',
                'type' => 'url',
                'label' => 'All Field Notes Button URL',
            ],

            // ==========================================
            // 2. ABOUT US PAGE
            // ==========================================
            [
                'page' => 'about',
                'section' => 'overview',
                'key' => 'badge',
                'value' => 'Corporate Overview',
                'type' => 'text',
                'label' => 'Overview Badge',
            ],
            [
                'page' => 'about',
                'section' => 'overview',
                'key' => 'title',
                'value' => 'Building Infrastructure That Endures For Generations',
                'type' => 'text',
                'label' => 'Overview Title',
            ],
            [
                'page' => 'about',
                'section' => 'overview',
                'key' => 'content',
                'value' => 'Founded with a vision to revolutionize metropolitan infrastructure, our firm operates across structural engineering, architectural modeling, heavy foundation piling, and general project management.',
                'type' => 'textarea',
                'label' => 'Company Narrative',
            ],
            [
                'page' => 'about',
                'section' => 'mission_vision',
                'key' => 'mission_title',
                'value' => 'Our Mission',
                'type' => 'text',
                'label' => 'Mission Title',
            ],
            [
                'page' => 'about',
                'section' => 'mission_vision',
                'key' => 'mission_content',
                'value' => 'To engineer and construct resilient, cost-effective, and aesthetically exceptional structures while adhering to world-class safety protocols.',
                'type' => 'textarea',
                'label' => 'Mission Statement',
            ],
            [
                'page' => 'about',
                'section' => 'mission_vision',
                'key' => 'vision_title',
                'value' => 'Our Vision',
                'type' => 'text',
                'label' => 'Vision Title',
            ],
            [
                'page' => 'about',
                'section' => 'mission_vision',
                'key' => 'vision_content',
                'value' => 'To be the benchmark of engineering excellence and sustainable urban innovation across the region.',
                'type' => 'textarea',
                'label' => 'Vision Statement',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'value_1_title',
                'value' => 'Structural Safety First',
                'type' => 'text',
                'label' => 'Value 1 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'value_1_desc',
                'value' => 'Zero-compromise protocols and continuous geotechnical assessments across all active worksites.',
                'type' => 'textarea',
                'label' => 'Value 1 Description',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'value_2_title',
                'value' => 'Integrity & Transparency',
                'type' => 'text',
                'label' => 'Value 2 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'value_2_desc',
                'value' => 'Transparent material testing logs, direct superintendent communication, and itemized billing.',
                'type' => 'textarea',
                'label' => 'Value 2 Description',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'value_3_title',
                'value' => 'Engineering Innovation',
                'type' => 'text',
                'label' => 'Value 3 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'value_3_desc',
                'value' => 'Leveraging advanced BIM modeling, drone site surveying, and modular prefabrication.',
                'type' => 'textarea',
                'label' => 'Value 3 Description',
            ],
            [
                'page' => 'about',
                'section' => 'history',
                'key' => 'milestone_1_year',
                'value' => '2012',
                'type' => 'text',
                'label' => 'Milestone 1 Year',
            ],
            [
                'page' => 'about',
                'section' => 'history',
                'key' => 'milestone_1_title',
                'value' => 'Enterprise Inception',
                'type' => 'text',
                'label' => 'Milestone 1 Title',
            ],
            [
                'page' => 'about',
                'section' => 'history',
                'key' => 'milestone_1_desc',
                'value' => 'Founded as a specialized structural consulting and foundation piling contractor.',
                'type' => 'textarea',
                'label' => 'Milestone 1 Description',
            ],
            [
                'page' => 'about',
                'section' => 'history',
                'key' => 'milestone_2_year',
                'value' => '2020',
                'type' => 'text',
                'label' => 'Milestone 2 Year',
            ],
            [
                'page' => 'about',
                'section' => 'history',
                'key' => 'milestone_2_title',
                'value' => 'Commercial Mega-Projects Expansion',
                'type' => 'text',
                'label' => 'Milestone 2 Title',
            ],
            [
                'page' => 'about',
                'section' => 'history',
                'key' => 'milestone_2_desc',
                'value' => 'Expanded into multi-story commercial towers, logistics hubs, and civic infrastructure projects.',
                'type' => 'textarea',
                'label' => 'Milestone 2 Description',
            ],

            // ==========================================
            // 3. CONTACT PAGE
            // ==========================================
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'badge',
                'value' => 'Direct Inquiries',
                'type' => 'text',
                'label' => 'Contact Intro Badge',
            ],
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'title',
                'value' => 'Connect With Our Field Operations & Estimations Team',
                'type' => 'text',
                'label' => 'Contact Heading',
            ],
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'description',
                'value' => 'Submit blueprints, request tender estimates, or schedule an on-site geotechnical inspection with our senior site engineers.',
                'type' => 'textarea',
                'label' => 'Contact Description',
            ],
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'sla_text',
                'value' => 'Average response time: within 4 business hours',
                'type' => 'text',
                'label' => 'Response SLA Notice',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'office_name',
                'value' => 'Metropolitan Engineering Headquarters',
                'type' => 'text',
                'label' => 'Office Center Name',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'working_hours',
                'value' => 'Mon - Sat: 08:00 AM - 06:00 PM',
                'type' => 'text',
                'label' => 'Working Operating Hours',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'address',
                'value' => '742 Evergreen Terrace, Sector 4, Metropolitan Zone, NY 10001',
                'type' => 'textarea',
                'label' => 'Office Physical Address',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'map_embed_url',
                'value' => 'https://maps.google.com',
                'type' => 'url',
                'label' => 'Google Maps URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'facebook',
                'value' => 'https://facebook.com',
                'type' => 'url',
                'label' => 'Facebook URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'linkedin',
                'value' => 'https://linkedin.com',
                'type' => 'url',
                'label' => 'LinkedIn URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'instagram',
                'value' => 'https://instagram.com',
                'type' => 'url',
                'label' => 'Instagram URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'youtube',
                'value' => 'https://youtube.com',
                'type' => 'url',
                'label' => 'YouTube URL',
            ],

            // ==========================================
            // 4. FOOTER & GLOBAL
            // ==========================================
            [
                'page' => 'footer',
                'section' => 'cta',
                'key' => 'headline',
                'value' => 'Ready To Start Your Next Commercial Build?',
                'type' => 'text',
                'label' => 'Footer CTA Headline',
            ],
            [
                'page' => 'footer',
                'section' => 'cta',
                'key' => 'btn_text',
                'value' => 'Discuss Project',
                'type' => 'text',
                'label' => 'Footer CTA Button Text',
            ],
            [
                'page' => 'footer',
                'section' => 'cta',
                'key' => 'btn_url',
                'value' => '#hero-content',
                'type' => 'url',
                'label' => 'Footer CTA Button URL',
            ],
            [
                'page' => 'footer',
                'section' => 'brand_bio',
                'key' => 'about_company',
                'value' => 'Commercial construction, structural engineering, and general contracting across metropolitan developments.',
                'type' => 'textarea',
                'label' => 'Footer Company Bio',
            ],
            [
                'page' => 'footer',
                'section' => 'newsletter',
                'key' => 'headline',
                'value' => 'Subscribe to Engineering & Construction Briefings',
                'type' => 'text',
                'label' => 'Newsletter Headline',
            ],
            [
                'page' => 'footer',
                'section' => 'newsletter',
                'key' => 'description',
                'value' => 'Get monthly insights on structural engineering breakthroughs, BIM technologies, and regional project tenders.',
                'type' => 'textarea',
                'label' => 'Newsletter Subtext',
            ],
            [
                'page' => 'footer',
                'section' => 'copyright',
                'key' => 'copyright_text',
                'value' => '© 2026 Building & Co. Construction Enterprise. All rights reserved.',
                'type' => 'text',
                'label' => 'Footer Copyright Text',
            ],

            // ==========================================
            // 5. SEO & META TAGS
            // ==========================================
            [
                'page' => 'seo',
                'section' => 'meta',
                'key' => 'meta_title',
                'value' => 'Building & Co. - Civil Engineering & Premier Construction Enterprise',
                'type' => 'text',
                'label' => 'Global Meta Title',
            ],
            [
                'page' => 'seo',
                'section' => 'meta',
                'key' => 'meta_description',
                'value' => 'Leading commercial construction, structural engineering, geotechnical site management, and architectural excellence in urban development.',
                'type' => 'textarea',
                'label' => 'Global Meta Description',
            ],
            [
                'page' => 'seo',
                'section' => 'meta',
                'key' => 'meta_keywords',
                'value' => 'construction, civil engineering, structural engineering, commercial towers, building contractors, BIM modeling, infrastructure',
                'type' => 'text',
                'label' => 'Target SEO Keywords',
            ],
            [
                'page' => 'seo',
                'section' => 'og',
                'key' => 'og_title',
                'value' => 'Building & Co. - Engineering Landmark Structures',
                'type' => 'text',
                'label' => 'OpenGraph Social Title',
            ],
            [
                'page' => 'seo',
                'section' => 'og',
                'key' => 'og_description',
                'value' => 'Explore premier civil engineering, architectural mastery, and construction capabilities.',
                'type' => 'textarea',
                'label' => 'OpenGraph Social Description',
            ],
        ];

        foreach ($contents as $item) {
            WebsiteContent::updateOrCreate(
                [
                    'page' => $item['page'],
                    'section' => $item['section'],
                    'key' => $item['key'],
                ],
                [
                    'value' => $item['value'],
                    'type' => $item['type'],
                    'label' => $item['label'],
                ]
            );
        }

        WebsiteContent::clearPageCache();
    }
}
