<?php

namespace Database\Seeders;

use App\Models\WebsiteContent;
use Illuminate\Database\Seeder;

class WebsiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds with exact website homepage content.
     */
    public function run(): void
    {
        $contents = [
            // ==========================================
            // 1. HOMEPAGE CONTENT (100% Website Aligned)
            // ==========================================

            // 1.1 Hero Section
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'badge',
                'value' => 'CONSTRUCTION & DEVELOPMENT',
                'type' => 'text',
                'label' => 'Hero Eyebrow / Badge',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'headline',
                'value' => 'Construction, from planning to completion.',
                'type' => 'text',
                'label' => 'Hero Main Heading',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'subheadline',
                'value' => 'Projects delivered with careful planning, clear coordination and attention to detail.',
                'type' => 'textarea',
                'label' => 'Hero Subheadline / Paragraph',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'primary_btn_text',
                'value' => 'View Projects',
                'type' => 'text',
                'label' => 'Primary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'primary_btn_url',
                'value' => '#projects',
                'type' => 'url',
                'label' => 'Primary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'secondary_btn_text',
                'value' => 'Contact Us',
                'type' => 'text',
                'label' => 'Secondary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'secondary_btn_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'Secondary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'stat_number',
                'value' => '24k+',
                'type' => 'text',
                'label' => 'Hero Floating Stat Number',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'stat_label',
                'value' => 'Project Success',
                'type' => 'text',
                'label' => 'Hero Floating Stat Label',
            ],
            [
                'page' => 'home',
                'section' => 'hero',
                'key' => 'stamp_text',
                'value' => '• EXPLORE WORK • VIEW PROJECTS',
                'type' => 'text',
                'label' => 'Hero Circular Rotating Stamp Text',
            ],

            // 1.2 About Section
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'badge',
                'value' => 'ABOUT CONSTRUCTION',
                'type' => 'text',
                'label' => 'About Section Badge',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'title',
                'value' => 'Construction built around precision, planning & detail.',
                'type' => 'text',
                'label' => 'About Heading Title',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'highlight_word',
                'value' => 'precision,',
                'type' => 'text',
                'label' => 'Highlighted Sketch Word',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'description',
                'value' => 'We approach every project with careful planning, coordinated execution and close attention to the details that shape the finished work.',
                'type' => 'textarea',
                'label' => 'About Lead Description',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'btn_text',
                'value' => 'DISCOVER MORE',
                'type' => 'text',
                'label' => 'About Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'btn_url',
                'value' => '#projects',
                'type' => 'url',
                'label' => 'About Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_years',
                'value' => '12',
                'type' => 'text',
                'label' => 'Experience Years Number',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Experience Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_title',
                'value' => 'Years of',
                'type' => 'text',
                'label' => 'Experience Title Line',
            ],
            [
                'page' => 'home',
                'section' => 'about_story',
                'key' => 'exp_subtitle',
                'value' => 'Experience.',
                'type' => 'text',
                'label' => 'Experience Subtitle Line',
            ],

            // 1.3 Features / Interior Execution
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'badge',
                'value' => 'Interior Execution',
                'type' => 'text',
                'label' => 'Features Badge',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'title',
                'value' => 'Interior Work, From Plan To Finish',
                'type' => 'text',
                'label' => 'Features Heading Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'quote',
                'value' => '“Coordinated drywall framing, MEP routing & architectural finishes delivered to spec.”',
                'type' => 'textarea',
                'label' => 'CEO Floating Quote',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'author_name',
                'value' => 'Alexander Joseph Reed',
                'type' => 'text',
                'label' => 'Author Name',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'author_title',
                'value' => 'Founder & CEO',
                'type' => 'text',
                'label' => 'Author Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_1_title',
                'value' => 'Structural Accuracy & Detailing',
                'type' => 'text',
                'label' => 'Feature 1 Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_1_desc',
                'value' => 'Detailed shop drawings and rebar schedules for clean on-site fabrication.',
                'type' => 'textarea',
                'label' => 'Feature 1 Description',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_2_title',
                'value' => 'Spatial & MEP Coordination',
                'type' => 'text',
                'label' => 'Feature 2 Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_2_desc',
                'value' => 'Clash-free routing between structural reinforced concrete and mechanical runs.',
                'type' => 'textarea',
                'label' => 'Feature 2 Description',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_3_title',
                'value' => 'Modular Prefabrication',
                'type' => 'text',
                'label' => 'Feature 3 Title',
            ],
            [
                'page' => 'home',
                'section' => 'features',
                'key' => 'feature_3_desc',
                'value' => 'Pre-assembled steel sections reducing active crane time and floor cycles.',
                'type' => 'textarea',
                'label' => 'Feature 3 Description',
            ],

            // 1.4 Experience & Results Section
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'badge',
                'value' => 'Project Track Record',
                'type' => 'text',
                'label' => 'Track Record Badge',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'title',
                'value' => 'Planned Work. Controlled Execution.',
                'type' => 'text',
                'label' => 'Section Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'description',
                'value' => 'We coordinate heavy equipment, civil trades, and structural crews to maintain strict schedule milestones from initial ground prep to final building handover.',
                'type' => 'textarea',
                'label' => 'Lead Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'primary_btn_text',
                'value' => 'DISCUSS A PROJECT',
                'type' => 'text',
                'label' => 'Primary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'primary_btn_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'Primary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'secondary_btn_text',
                'value' => 'VIEW RECENT SITES',
                'type' => 'text',
                'label' => 'Secondary Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'secondary_btn_url',
                'value' => '#projects',
                'type' => 'url',
                'label' => 'Secondary Button URL',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_count',
                'value' => '240',
                'type' => 'text',
                'label' => 'Metric 1 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Metric 1 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_title',
                'value' => 'Commercial Builds',
                'type' => 'text',
                'label' => 'Metric 1 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_1_desc',
                'value' => 'Delivered under direct site supervision.',
                'type' => 'text',
                'label' => 'Metric 1 Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_count',
                'value' => '99',
                'type' => 'text',
                'label' => 'Metric 2 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_suffix',
                'value' => '%',
                'type' => 'text',
                'label' => 'Metric 2 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_title',
                'value' => 'Milestone Compliance',
                'type' => 'text',
                'label' => 'Metric 2 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_2_desc',
                'value' => 'On-schedule stage completions & handovers.',
                'type' => 'text',
                'label' => 'Metric 2 Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_count',
                'value' => '12',
                'type' => 'text',
                'label' => 'Metric 3 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Metric 3 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_title',
                'value' => 'Years In Field',
                'type' => 'text',
                'label' => 'Metric 3 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_3_desc',
                'value' => 'Continuous active contractor operations.',
                'type' => 'text',
                'label' => 'Metric 3 Description',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_count',
                'value' => '180',
                'type' => 'text',
                'label' => 'Metric 4 Counter',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Metric 4 Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_title',
                'value' => 'Trade Specialists',
                'type' => 'text',
                'label' => 'Metric 4 Title',
            ],
            [
                'page' => 'home',
                'section' => 'experience',
                'key' => 'stat_4_desc',
                'value' => 'Certified steel erectors, formworkers & operators.',
                'type' => 'text',
                'label' => 'Metric 4 Description',
            ],

            // 1.5 Services Section Header
            [
                'page' => 'home',
                'section' => 'services',
                'key' => 'badge',
                'value' => 'CORE CAPABILITIES',
                'type' => 'text',
                'label' => 'Services Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'services',
                'key' => 'title',
                'value' => 'Structured Scopes. Direct Site Execution.',
                'type' => 'text',
                'label' => 'Services Headline',
            ],
            [
                'page' => 'home',
                'section' => 'services',
                'key' => 'subtitle',
                'value' => 'Clear project scopes, realistic floor cycle timelines, and full-time site superintendence for commercial and structural projects.',
                'type' => 'textarea',
                'label' => 'Services Lead Description',
            ],

            // 1.6 Projects Section Header
            [
                'page' => 'home',
                'section' => 'projects',
                'key' => 'badge',
                'value' => 'RECENT PROJECTS',
                'type' => 'text',
                'label' => 'Projects Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'projects',
                'key' => 'title',
                'value' => 'Featured Engineering & Construction Work',
                'type' => 'text',
                'label' => 'Projects Headline',
            ],
            [
                'page' => 'home',
                'section' => 'projects',
                'key' => 'subtitle',
                'value' => 'Explore our signature portfolio of commercial towers, industrial logistics facilities, civic architecture, and civil infrastructure.',
                'type' => 'textarea',
                'label' => 'Projects Lead Description',
            ],

            // 1.7 Testimonials Header & Metrics
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'watermark',
                'value' => 'FEEDBACK',
                'type' => 'text',
                'label' => 'Testimonials Watermark',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'eyebrow',
                'value' => 'Client Feedback',
                'type' => 'text',
                'label' => 'Testimonials Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'title',
                'value' => 'Direct Feedback From <br> Project <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Owners</span> &amp; Developers',
                'type' => 'textarea',
                'label' => 'Testimonials Headline',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'stat_count',
                'value' => '12',
                'type' => 'text',
                'label' => 'Testimonials Metric Count',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'stat_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Testimonials Metric Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'testimonials',
                'key' => 'stat_desc',
                'value' => 'Years of repeat commercial developer partnerships and general contracting delivery.',
                'type' => 'textarea',
                'label' => 'Testimonials Metric Description',
            ],

            // 1.8 Why Choose Us Section
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'watermark',
                'value' => 'EXPERTISE',
                'type' => 'text',
                'label' => 'Why Choose Us Watermark',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'badge',
                'value' => 'Our Approach',
                'type' => 'text',
                'label' => 'Why Choose Us Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'title_prefix',
                'value' => 'Practical Construction,',
                'type' => 'text',
                'label' => 'Title Prefix',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'highlight_word',
                'value' => 'Carefully',
                'type' => 'text',
                'label' => 'Title Highlighted Word',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'title_suffix',
                'value' => 'Delivered',
                'type' => 'text',
                'label' => 'Title Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'description',
                'value' => 'We manage builds through accurate material planning, direct trade superintendence, and clear milestone reporting from groundbreaking to project closeout.',
                'type' => 'textarea',
                'label' => 'Why Choose Us Lead Description',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'stat_count',
                'value' => '22',
                'type' => 'text',
                'label' => 'Completed Builds Stat Number',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'stat_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Completed Builds Suffix',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'stat_label',
                'value' => 'Completed Builds',
                'type' => 'text',
                'label' => 'Completed Builds Label',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_1_title',
                'value' => 'Tested Materials & Sourcing',
                'type' => 'text',
                'label' => 'Feature 1 Title',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_1_desc',
                'value' => 'Certified grade structural steel, batch-tested concrete, and verified supplier supply chains.',
                'type' => 'textarea',
                'label' => 'Feature 1 Description',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_2_title',
                'value' => 'On-Site Superintendent Control',
                'type' => 'text',
                'label' => 'Feature 2 Title',
            ],
            [
                'page' => 'home',
                'section' => 'why_choose_us',
                'key' => 'feature_2_desc',
                'value' => 'Full-time field engineers reviewing structural tolerances, subcontractor safety, and daily QA logs.',
                'type' => 'textarea',
                'label' => 'Feature 2 Description',
            ],

            // 1.9 News & Field Logs Header
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'watermark',
                'value' => 'UPDATES',
                'type' => 'text',
                'label' => 'News Section Watermark',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'eyebrow',
                'value' => 'Field Logs & Updates',
                'type' => 'text',
                'label' => 'News Section Eyebrow',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'title',
                'value' => 'Jobsite Notes, Methods &amp; <br> <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Field</span> Updates',
                'type' => 'textarea',
                'label' => 'News Section Title',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'button_text',
                'value' => 'All Field Notes',
                'type' => 'text',
                'label' => 'All Field Notes Button Text',
            ],
            [
                'page' => 'home',
                'section' => 'news',
                'key' => 'button_url',
                'value' => '#news',
                'type' => 'url',
                'label' => 'All Field Notes Button URL',
            ],

            // ==========================================
            // 2. ABOUT US PAGE
            // ==========================================

            // 2.1 About Hero Banner
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'watermark',
                'value' => 'HERITAGE',
                'type' => 'text',
                'label' => 'Hero Watermark Text',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'badge',
                'value' => 'ABOUT OUR ENTERPRISE',
                'type' => 'text',
                'label' => 'Hero Eyebrow / Badge',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'title',
                'value' => 'Engineering Structures With <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.15em] tracking-normal inline-block transform -rotate-1">Uncompromising</span> Precision.',
                'type' => 'textarea',
                'label' => 'Hero Main Title',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'description',
                'value' => 'For over a decade, we have partnered with institutional developers and project owners to deliver high-performance commercial towers, industrial hubs, and resilient civic infrastructure.',
                'type' => 'textarea',
                'label' => 'Hero Description',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'btn_1_text',
                'value' => "Chairman's Speech",
                'type' => 'text',
                'label' => 'Primary Button Text',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'btn_1_url',
                'value' => '#chairmans-message',
                'type' => 'url',
                'label' => 'Primary Button URL',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'btn_2_text',
                'value' => 'Our Standards',
                'type' => 'text',
                'label' => 'Secondary Button Text',
            ],
            [
                'page' => 'about',
                'section' => 'hero',
                'key' => 'btn_2_url',
                'value' => '#core-values',
                'type' => 'url',
                'label' => 'Secondary Button URL',
            ],

            // 2.2 Corporate Narrative & Origins
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'watermark',
                'value' => 'ORIGINS',
                'type' => 'text',
                'label' => 'Story Watermark Text',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'badge',
                'value' => 'Our Origins & Mission',
                'type' => 'text',
                'label' => 'Story Eyebrow Badge',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'title',
                'value' => 'Pioneering Heavy Civil & <br>Commercial <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Execution</span>',
                'type' => 'textarea',
                'label' => 'Story Main Title',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'description_1',
                'value' => 'Established in 2012, Antigravity Construction began with a disciplined focus on deep foundation engineering, geotechnical stabilization, and structural reinforced concrete frames.',
                'type' => 'textarea',
                'label' => 'Story First Paragraph',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'description_2',
                'value' => 'Today, our integrated multidisciplinary engineering and superintendent teams manage full-lifecycle EPC contracts across major metropolitan sectors. We eliminate construction risk through rigorous 5D BIM clash detection, daily QA/QC inspection regimes, and zero-compromise site safety governance.',
                'type' => 'textarea',
                'label' => 'Story Second Paragraph',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'checklist_1',
                'value' => 'Direct Field Supervision',
                'type' => 'text',
                'label' => 'Checklist Item 1',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'checklist_2',
                'value' => '100% In-House Heavy Plant',
                'type' => 'text',
                'label' => 'Checklist Item 2',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'checklist_3',
                'value' => 'BIM 5D Digital Telemetry',
                'type' => 'text',
                'label' => 'Checklist Item 3',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'checklist_4',
                'value' => 'Milestone Guarantee',
                'type' => 'text',
                'label' => 'Checklist Item 4',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'exp_years',
                'value' => '12',
                'type' => 'text',
                'label' => 'Experience Years Counter',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'exp_suffix',
                'value' => '+',
                'type' => 'text',
                'label' => 'Experience Suffix',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'exp_title',
                'value' => 'Years of Continuous',
                'type' => 'text',
                'label' => 'Experience Card Title',
            ],
            [
                'page' => 'about',
                'section' => 'story',
                'key' => 'exp_subtitle',
                'value' => 'Contractor Delivery.',
                'type' => 'text',
                'label' => 'Experience Card Subtitle',
            ],

            // 2.3 Chairman's Speech & Leadership Vision
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'watermark',
                'value' => 'VISION',
                'type' => 'text',
                'label' => 'Chairman Speech Watermark',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'badge',
                'value' => "Chairman's Address",
                'type' => 'text',
                'label' => 'Chairman Section Eyebrow',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'title',
                'value' => 'Building With Purpose, <br>Delivering With <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Integrity</span>',
                'type' => 'textarea',
                'label' => 'Chairman Speech Heading',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'speech_p1',
                'value' => 'When we established this enterprise over twelve years ago, our guiding conviction was simple: exceptional construction is not merely about pouring concrete or assembling structural steel—it is about honoring the trust placed in us by developers, communities, and future generations who will inhabit these spaces.',
                'type' => 'textarea',
                'label' => 'Speech Paragraph 1',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'speech_p2',
                'value' => 'In an era where urban development demands unprecedented speed, precision, and sustainability, we have never allowed expediency to compromise structural integrity or worker safety. Every project site under our supervision operates as a sanctuary of discipline, modern engineering telemetry, and transparent communication.',
                'type' => 'textarea',
                'label' => 'Speech Paragraph 2',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'speech_p3',
                'value' => 'As we look toward the next decade, our focus remains steadfast on adopting low-carbon materials, 5D BIM digital workflows, and modular engineering innovations that shape iconic skylines while safeguarding environmental benchmarks. We thank our partners, engineers, and workforce for building this enduring legacy with us.',
                'type' => 'textarea',
                'label' => 'Speech Paragraph 3',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'quote_highlight',
                'value' => '“We measure our success not by the height of our towers, but by the permanence of our craftsmanship and the safety of every craftsman on our jobsites.”',
                'type' => 'textarea',
                'label' => 'Chairman Quotation Highlight',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'chairman_name',
                'value' => 'Alexander Joseph Reed',
                'type' => 'text',
                'label' => 'Chairman Name',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'chairman_role',
                'value' => 'Founder & Executive Chairman',
                'type' => 'text',
                'label' => 'Chairman Official Title',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'chairman_credentials',
                'value' => 'FIEB, CEng, MSc Structural Engineering',
                'type' => 'text',
                'label' => 'Chairman Academic & Professional Credentials',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'signature_name',
                'value' => 'Alexander J. Reed',
                'type' => 'text',
                'label' => 'Chairman Signature Name',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'signature_title',
                'value' => "Executive Chairman's Desk",
                'type' => 'text',
                'label' => 'Chairman Signature Title',
            ],
            [
                'page' => 'about',
                'section' => 'chairman_speech',
                'key' => 'est_badge',
                'value' => 'Est. 2012',
                'type' => 'text',
                'label' => 'Established Year Badge',
            ],

            // 2.4 Core Construction Principles & Values
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'watermark',
                'value' => 'STANDARDS',
                'type' => 'text',
                'label' => 'Values Watermark',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'badge',
                'value' => 'Our Pillars of Practice',
                'type' => 'text',
                'label' => 'Values Eyebrow Badge',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'title',
                'value' => 'Engineering Benchmarks That <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Define</span> Every Build',
                'type' => 'textarea',
                'label' => 'Values Main Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'subtitle',
                'value' => 'Four non-negotiable operational principles engineered into every deep foundation, reinforced frame, and commercial handover.',
                'type' => 'textarea',
                'label' => 'Values Subtitle',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_heading',
                'value' => 'Operational Benchmark Summary',
                'type' => 'text',
                'label' => 'Benchmark Summary Heading',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_1_label',
                'value' => '01 / Safety Discipline',
                'type' => 'text',
                'label' => 'Summary 1 Label',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_1_val',
                'value' => 'Zero-Incident HSE',
                'type' => 'text',
                'label' => 'Summary 1 Value',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_2_label',
                'value' => '02 / Digital Engineering',
                'type' => 'text',
                'label' => 'Summary 2 Label',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_2_val',
                'value' => 'BIM 5D · LOD 400',
                'type' => 'text',
                'label' => 'Summary 2 Value',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_3_label',
                'value' => '03 / Material Quality',
                'type' => 'text',
                'label' => 'Summary 3 Label',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_3_val',
                'value' => '65+ MPa Verified',
                'type' => 'text',
                'label' => 'Summary 3 Value',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_4_label',
                'value' => '04 / Schedule Control',
                'type' => 'text',
                'label' => 'Summary 4 Label',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'summary_4_val',
                'value' => 'Critical-Path CPM',
                'type' => 'text',
                'label' => 'Summary 4 Value',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_1_title',
                'value' => 'Zero-Incident HSE Governance',
                'type' => 'text',
                'label' => 'Value 1 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_1_desc',
                'value' => 'Proactive safety audits, computerized strut telemetry, and mandatory daily tool-box briefings across every live tier.',
                'type' => 'textarea',
                'label' => 'Value 1 Description',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_1_tag_1',
                'value' => 'Daily Toolbox Audits',
                'type' => 'text',
                'label' => 'Value 1 Tag 1',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_1_tag_2',
                'value' => 'Automated Strut Telemetry',
                'type' => 'text',
                'label' => 'Value 1 Tag 2',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_1_tag_3',
                'value' => 'ISO 45001',
                'type' => 'text',
                'label' => 'Value 1 Tag 3',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_2_title',
                'value' => 'BIM 5D & Clash Detection',
                'type' => 'text',
                'label' => 'Value 2 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_2_desc',
                'value' => '3D point cloud LIDAR drone scans mapped to Revit IFC models preventing costly field MEP clashes.',
                'type' => 'textarea',
                'label' => 'Value 2 Description',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_2_tag_1',
                'value' => '3D Point Cloud Drone Scans',
                'type' => 'text',
                'label' => 'Value 2 Tag 1',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_2_tag_2',
                'value' => 'LOD 400 Digital Twins',
                'type' => 'text',
                'label' => 'Value 2 Tag 2',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_2_tag_3',
                'value' => 'Zero MEP Collisions',
                'type' => 'text',
                'label' => 'Value 2 Tag 3',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_3_title',
                'value' => 'Tested Materials Sourcing',
                'type' => 'text',
                'label' => 'Value 3 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_3_desc',
                'value' => 'Certified post-tensioned high-tensile steel and third-party laboratory verified 65+ MPa concrete cube testing.',
                'type' => 'textarea',
                'label' => 'Value 3 Description',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_3_tag_1',
                'value' => '65+ MPa Concrete Crush Tests',
                'type' => 'text',
                'label' => 'Value 3 Tag 1',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_3_tag_2',
                'value' => 'High-Tensile Rebar',
                'type' => 'text',
                'label' => 'Value 3 Tag 2',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_3_tag_3',
                'value' => 'ASTM C39 QA',
                'type' => 'text',
                'label' => 'Value 3 Tag 3',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_4_title',
                'value' => 'Critical-Path Milestone Control',
                'type' => 'text',
                'label' => 'Value 4 Title',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_4_desc',
                'value' => 'Full-time site superintendents providing real-time stage lookahead schedules and transparent owner reporting.',
                'type' => 'textarea',
                'label' => 'Value 4 Description',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_4_tag_1',
                'value' => 'Full-Time Site Superintendents',
                'type' => 'text',
                'label' => 'Value 4 Tag 1',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_4_tag_2',
                'value' => '4-Week Lookahead Matrix',
                'type' => 'text',
                'label' => 'Value 4 Tag 2',
            ],
            [
                'page' => 'about',
                'section' => 'values',
                'key' => 'val_4_tag_3',
                'value' => 'Milestone Guarantee',
                'type' => 'text',
                'label' => 'Value 4 Tag 3',
            ],

            // 2.5 Milestones Journey Timeline
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'watermark',
                'value' => 'JOURNEY',
                'type' => 'text',
                'label' => 'Timeline Watermark',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'badge',
                'value' => 'Evolution of Excellence',
                'type' => 'text',
                'label' => 'Timeline Eyebrow Badge',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'title',
                'value' => 'Milestones of Proven <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Growth</span> & Capability',
                'type' => 'textarea',
                'label' => 'Timeline Main Title',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'intro',
                'value' => 'From specialized deep geotechnical foundation works to managing full-scale commercial EPC developments, our journey represents a continuous commitment to precision engineering, modern telemetry, and structural integrity.',
                'type' => 'textarea',
                'label' => 'Timeline Intro Description',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_1_year',
                'value' => '2012',
                'type' => 'text',
                'label' => 'Timeline Item 1 Year',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_1_title',
                'value' => 'Enterprise Founding & Geotechnical Inception',
                'type' => 'text',
                'label' => 'Timeline Item 1 Title',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_1_desc',
                'value' => 'Commenced operations specializing in high-capacity cast-in-situ bored piling and complex basement shoring solutions.',
                'type' => 'textarea',
                'label' => 'Timeline Item 1 Description',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_2_year',
                'value' => '2016',
                'type' => 'text',
                'label' => 'Timeline Item 2 Year',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_2_title',
                'value' => 'Expansion to Full General Contracting',
                'type' => 'text',
                'label' => 'Timeline Item 2 Title',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_2_desc',
                'value' => 'Mobilized dedicated structural, mechanical, and architectural superintendent divisions for full-scale commercial builds.',
                'type' => 'textarea',
                'label' => 'Timeline Item 2 Description',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_3_year',
                'value' => '2020',
                'type' => 'text',
                'label' => 'Timeline Item 3 Year',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_3_title',
                'value' => 'Commercial Mega-Towers & Industrial Hubs',
                'type' => 'text',
                'label' => 'Timeline Item 3 Title',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_3_desc',
                'value' => 'Completed 28-story corporate headquarters and 350,000 sq.ft automated logistics centers ahead of scheduled milestones.',
                'type' => 'textarea',
                'label' => 'Timeline Item 3 Description',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_4_year',
                'value' => '2024–Present',
                'type' => 'text',
                'label' => 'Timeline Item 4 Year',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_4_title',
                'value' => 'Smart Construction & Low-Carbon Engineering',
                'type' => 'text',
                'label' => 'Timeline Item 4 Title',
            ],
            [
                'page' => 'about',
                'section' => 'timeline',
                'key' => 'item_4_desc',
                'value' => 'Benchmarking geopolymer low-carbon mixes, autonomous drone surveys, and LEED Platinum smart civil infrastructure.',
                'type' => 'textarea',
                'label' => 'Timeline Item 4 Description',
            ],

            // 2.6 Executive Leadership Team
            [
                'page' => 'about',
                'section' => 'leadership',
                'key' => 'watermark',
                'value' => 'LEADERS',
                'type' => 'text',
                'label' => 'Leadership Watermark',
            ],
            [
                'page' => 'about',
                'section' => 'leadership',
                'key' => 'badge',
                'value' => 'OUR EXPERIENCE TEAM',
                'type' => 'text',
                'label' => 'Leadership Eyebrow Badge',
            ],
            [
                'page' => 'about',
                'section' => 'leadership',
                'key' => 'title',
                'value' => 'Leaders Driving Future <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Building Excellence</span>',
                'type' => 'textarea',
                'label' => 'Leadership Main Title',
            ],
            [
                'page' => 'about',
                'section' => 'leadership',
                'key' => 'team_label',
                'value' => 'TEAM MEMBER',
                'type' => 'text',
                'label' => 'Team Member Vertical Label',
            ],

            // 2.7 Accreditations & Honors
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'watermark',
                'value' => 'HONORS',
                'type' => 'text',
                'label' => 'Accreditations Watermark',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'badge',
                'value' => 'Accreditations & Honors',
                'type' => 'text',
                'label' => 'Accreditations Eyebrow Badge',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'title',
                'value' => 'Recognized Standards of <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Certified</span> Excellence',
                'type' => 'textarea',
                'label' => 'Accreditations Main Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'subtitle',
                'value' => 'A continuous record of engineering benchmarking, building excellence awards, and stringent quality protocols across enterprise commercial builds.',
                'type' => 'textarea',
                'label' => 'Accreditations Subtitle',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_1_year',
                'value' => '2024',
                'type' => 'text',
                'label' => 'Accreditation 1 Year',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_1_title',
                'value' => 'BUILD OF THE YEAR',
                'type' => 'text',
                'label' => 'Accreditation 1 Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_1_category',
                'value' => 'Commercial High-Rise Development',
                'type' => 'text',
                'label' => 'Accreditation 1 Category',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_1_status',
                'value' => 'Winner',
                'type' => 'text',
                'label' => 'Accreditation 1 Status',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_2_year',
                'value' => '2023',
                'type' => 'text',
                'label' => 'Accreditation 2 Year',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_2_title',
                'value' => 'TOP BUILD AWARD',
                'type' => 'text',
                'label' => 'Accreditation 2 Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_2_category',
                'value' => 'Sustainable Civil & Structural Engineering',
                'type' => 'text',
                'label' => 'Accreditation 2 Category',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_2_status',
                'value' => 'Winner',
                'type' => 'text',
                'label' => 'Accreditation 2 Status',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_3_year',
                'value' => '2022',
                'type' => 'text',
                'label' => 'Accreditation 3 Year',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_3_title',
                'value' => 'BEST DESIGN OF THE YEAR',
                'type' => 'text',
                'label' => 'Accreditation 3 Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_3_category',
                'value' => 'Architectural Innovation & BIM Execution',
                'type' => 'text',
                'label' => 'Accreditation 3 Category',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_3_status',
                'value' => 'Winner',
                'type' => 'text',
                'label' => 'Accreditation 3 Status',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_4_year',
                'value' => '2022',
                'type' => 'text',
                'label' => 'Accreditation 4 Year',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_4_title',
                'value' => 'BEST BUILDING PROJECT',
                'type' => 'text',
                'label' => 'Accreditation 4 Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_4_category',
                'value' => 'Industrial Logistics & Smart Hub Facility',
                'type' => 'text',
                'label' => 'Accreditation 4 Category',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_4_status',
                'value' => 'Winner',
                'type' => 'text',
                'label' => 'Accreditation 4 Status',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_5_year',
                'value' => '2021',
                'type' => 'text',
                'label' => 'Accreditation 5 Year',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_5_title',
                'value' => 'CONSTRUCTION HONORS',
                'type' => 'text',
                'label' => 'Accreditation 5 Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_5_category',
                'value' => 'Preconstruction & Safety Distinction',
                'type' => 'text',
                'label' => 'Accreditation 5 Category',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_5_status',
                'value' => 'Runner Up',
                'type' => 'text',
                'label' => 'Accreditation 5 Status',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_6_year',
                'value' => '2020',
                'type' => 'text',
                'label' => 'Accreditation 6 Year',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_6_title',
                'value' => 'ISO 9001 & LEED PLATINUM',
                'type' => 'text',
                'label' => 'Accreditation 6 Title',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_6_category',
                'value' => 'Quality Management & Green Compliance',
                'type' => 'text',
                'label' => 'Accreditation 6 Category',
            ],
            [
                'page' => 'about',
                'section' => 'accreditations',
                'key' => 'item_6_status',
                'value' => 'Certified',
                'type' => 'text',
                'label' => 'Accreditation 6 Status',
            ],

            // 2.8 About CTA Banner
            [
                'page' => 'about',
                'section' => 'cta',
                'key' => 'watermark',
                'value' => 'PARTNER',
                'type' => 'text',
                'label' => 'CTA Watermark',
            ],
            [
                'page' => 'about',
                'section' => 'cta',
                'key' => 'eyebrow',
                'value' => 'Start Your Development',
                'type' => 'text',
                'label' => 'CTA Eyebrow Badge',
            ],
            [
                'page' => 'about',
                'section' => 'cta',
                'key' => 'title',
                'value' => 'Ready to build with certainty, schedule <br>discipline & structural excellence?',
                'type' => 'textarea',
                'label' => 'CTA Title',
            ],
            [
                'page' => 'about',
                'section' => 'cta',
                'key' => 'description',
                'value' => 'Schedule a technical consultation with our senior project estimators and structural engineers for your upcoming commercial tender.',
                'type' => 'textarea',
                'label' => 'CTA Description',
            ],
            [
                'page' => 'about',
                'section' => 'cta',
                'key' => 'btn_text',
                'value' => 'Request Project Tender',
                'type' => 'text',
                'label' => 'CTA Button Text',
            ],
            [
                'page' => 'about',
                'section' => 'cta',
                'key' => 'btn_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'CTA Button URL',
            ],

            // ==========================================
            // 3. CONTACT PAGE
            // ==========================================
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'badge',
                'value' => 'Direct Inquiries',
                'type' => 'text',
                'label' => 'Contact Intro Badge',
            ],
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'title',
                'value' => 'Connect With Our Field Operations & Estimations Team',
                'type' => 'text',
                'label' => 'Contact Heading',
            ],
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'description',
                'value' => 'Submit blueprints, request tender estimates, or schedule an on-site geotechnical inspection with our senior site engineers.',
                'type' => 'textarea',
                'label' => 'Contact Description',
            ],
            [
                'page' => 'contact',
                'section' => 'intro',
                'key' => 'sla_text',
                'value' => 'Average response time: within 4 business hours',
                'type' => 'text',
                'label' => 'Response SLA Notice',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'office_name',
                'value' => 'Metropolitan Engineering Headquarters',
                'type' => 'text',
                'label' => 'Office Center Name',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'working_hours',
                'value' => 'Mon - Sat: 08:00 AM - 06:00 PM',
                'type' => 'text',
                'label' => 'Working Operating Hours',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'address',
                'value' => '742 Evergreen Terrace, Sector 4, Metropolitan Zone, NY 10001',
                'type' => 'textarea',
                'label' => 'Office Physical Address',
            ],
            [
                'page' => 'contact',
                'section' => 'office',
                'key' => 'map_embed_url',
                'value' => 'https://maps.google.com',
                'type' => 'url',
                'label' => 'Google Maps URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'facebook',
                'value' => 'https://facebook.com',
                'type' => 'url',
                'label' => 'Facebook URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'linkedin',
                'value' => 'https://linkedin.com',
                'type' => 'url',
                'label' => 'LinkedIn URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'instagram',
                'value' => 'https://instagram.com',
                'type' => 'url',
                'label' => 'Instagram URL',
            ],
            [
                'page' => 'contact',
                'section' => 'social',
                'key' => 'youtube',
                'value' => 'https://youtube.com',
                'type' => 'url',
                'label' => 'YouTube URL',
            ],

            // ==========================================
            // 4. FOOTER & GLOBAL
            // ==========================================
            [
                'page' => 'footer',
                'section' => 'cta',
                'key' => 'headline',
                'value' => 'Ready To Start Your Next Commercial Build?',
                'type' => 'text',
                'label' => 'Footer CTA Headline',
            ],
            [
                'page' => 'footer',
                'section' => 'cta',
                'key' => 'btn_text',
                'value' => 'Discuss Project',
                'type' => 'text',
                'label' => 'Footer CTA Button Text',
            ],
            [
                'page' => 'footer',
                'section' => 'cta',
                'key' => 'btn_url',
                'value' => '#hero-content',
                'type' => 'url',
                'label' => 'Footer CTA Button URL',
            ],
            [
                'page' => 'footer',
                'section' => 'brand_bio',
                'key' => 'about_company',
                'value' => 'Commercial construction, structural engineering, and general contracting across metropolitan developments.',
                'type' => 'textarea',
                'label' => 'Footer Company Bio',
            ],
            [
                'page' => 'footer',
                'section' => 'newsletter',
                'key' => 'headline',
                'value' => 'Subscribe to Engineering & Construction Briefings',
                'type' => 'text',
                'label' => 'Newsletter Headline',
            ],
            [
                'page' => 'footer',
                'section' => 'newsletter',
                'key' => 'description',
                'value' => 'Get monthly insights on structural engineering breakthroughs, BIM technologies, and regional project tenders.',
                'type' => 'textarea',
                'label' => 'Newsletter Subtext',
            ],
            [
                'page' => 'footer',
                'section' => 'copyright',
                'key' => 'copyright_text',
                'value' => '© 2026 Building & Co. Construction Enterprise. All rights reserved.',
                'type' => 'text',
                'label' => 'Footer Copyright Text',
            ],

            // ==========================================
            // 4. PROJECTS PAGE
            // ==========================================

            // 4.1 Hero Section
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'watermark',
                'value' => 'BUILDS',
                'type' => 'text',
                'label' => 'Projects Hero Watermark',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'badge',
                'value' => 'PROJECT PORTFOLIO & CASE STUDIES',
                'type' => 'text',
                'label' => 'Projects Hero Eyebrow Badge',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'title',
                'value' => 'Engineering Skylines, Infrastructure & <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.15em] tracking-normal inline-block transform -rotate-1">Sustainable</span> Landmarks.',
                'type' => 'textarea',
                'label' => 'Projects Hero Title',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'description',
                'value' => 'A comprehensive showcase of heavy civil engineering contracts, 28-story commercial headquarters, automated industrial fulfillment hubs, and coastal resilient infrastructure.',
                'type' => 'textarea',
                'label' => 'Projects Hero Description',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'stat_1_val',
                'value' => '100%',
                'type' => 'text',
                'label' => 'Hero Stat 1 Value',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'stat_1_label',
                'value' => 'Milestone Delivery Guarantee',
                'type' => 'text',
                'label' => 'Hero Stat 1 Label',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'stat_2_val',
                'value' => '420k+',
                'type' => 'text',
                'label' => 'Hero Stat 2 Value',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'stat_2_label',
                'value' => 'Sq.Ft Commercial Footprint',
                'type' => 'text',
                'label' => 'Hero Stat 2 Label',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'stat_3_val',
                'value' => 'Zero',
                'type' => 'text',
                'label' => 'Hero Stat 3 Value',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'stat_3_label',
                'value' => 'Lost-Time HSE Record',
                'type' => 'text',
                'label' => 'Hero Stat 3 Label',
            ],
            [
                'page' => 'projects',
                'section' => 'hero',
                'key' => 'bg_image',
                'value' => 'images/project-commercial-tower.jpg',
                'type' => 'image',
                'label' => 'Projects Hero Background Image',
            ],

            // 4.2 Projects Showcase Grid Header
            [
                'page' => 'projects',
                'section' => 'showcase',
                'key' => 'watermark',
                'value' => 'PORTFOLIO',
                'type' => 'text',
                'label' => 'Showcase Watermark',
            ],
            [
                'page' => 'projects',
                'section' => 'showcase',
                'key' => 'badge',
                'value' => 'SIGNATURE BUILDS',
                'type' => 'text',
                'label' => 'Showcase Eyebrow Badge',
            ],
            [
                'page' => 'projects',
                'section' => 'showcase',
                'key' => 'title',
                'value' => 'Disciplined Execution Across <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Diverse</span> Sectors',
                'type' => 'textarea',
                'label' => 'Showcase Section Title',
            ],
            [
                'page' => 'projects',
                'section' => 'showcase',
                'key' => 'subtitle',
                'value' => 'Filter our verified case studies by operational sector to explore structural blueprints, geotechnical specifications, and photographic construction timelines.',
                'type' => 'textarea',
                'label' => 'Showcase Subtitle',
            ],

            // 4.3 Flagship Project Spotlight
            [
                'page' => 'projects',
                'section' => 'spotlight',
                'key' => 'watermark',
                'value' => 'SPOTLIGHT',
                'type' => 'text',
                'label' => 'Spotlight Watermark',
            ],
            [
                'page' => 'projects',
                'section' => 'spotlight',
                'key' => 'badge',
                'value' => 'FLAGSHIP CASE STUDY',
                'type' => 'text',
                'label' => 'Spotlight Eyebrow Badge',
            ],
            [
                'page' => 'projects',
                'section' => 'spotlight',
                'key' => 'title',
                'value' => 'Engineering Excellence in <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">High-Density</span> Commercial Zones',
                'type' => 'textarea',
                'label' => 'Spotlight Main Title',
            ],
            [
                'page' => 'projects',
                'section' => 'spotlight',
                'key' => 'subtitle',
                'value' => 'A deep-dive analysis into the geotechnical stabilization, continuous raft pour telemetry, and dual-shear structural core of our premier commercial delivery.',
                'type' => 'textarea',
                'label' => 'Spotlight Subtitle',
            ],

            // 4.4 Project Index Matrix
            [
                'page' => 'projects',
                'section' => 'index_matrix',
                'key' => 'watermark',
                'value' => 'ARCHIVE',
                'type' => 'text',
                'label' => 'Index Matrix Watermark',
            ],
            [
                'page' => 'projects',
                'section' => 'index_matrix',
                'key' => 'badge',
                'value' => 'COMPLETE ARCHITECTURAL INDEX',
                'type' => 'text',
                'label' => 'Index Matrix Eyebrow Badge',
            ],
            [
                'page' => 'projects',
                'section' => 'index_matrix',
                'key' => 'title',
                'value' => 'Enterprise Project <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Directory</span> & Delivery Log',
                'type' => 'textarea',
                'label' => 'Index Matrix Title',
            ],
            [
                'page' => 'projects',
                'section' => 'index_matrix',
                'key' => 'subtitle',
                'value' => 'Hover over any contract record to preview construction imagery, location coordinates, client entities, and full engineering deliverables.',
                'type' => 'textarea',
                'label' => 'Index Matrix Subtitle',
            ],

            // 4.5 Engineering Standards & Delivery Assurance
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'watermark',
                'value' => 'RIGOR',
                'type' => 'text',
                'label' => 'Standards Watermark',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'badge',
                'value' => 'ENGINEERING ASSURANCE PROTOCOLS',
                'type' => 'text',
                'label' => 'Standards Eyebrow Badge',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'title',
                'value' => 'How We Guarantee Zero-Incident <br><span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">Structural</span> Integrity',
                'type' => 'textarea',
                'label' => 'Standards Main Title',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'subtitle',
                'value' => 'Every square meter of our job sites operates under computerized QA/QC inspection regimes, LIDAR drone surveys, and third-party laboratory verified material batches.',
                'type' => 'textarea',
                'label' => 'Standards Subtitle',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_1_title',
                'value' => '01 / BIM 5D Preconstruction Clash Detection',
                'type' => 'text',
                'label' => 'Standard 1 Title',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_1_desc',
                'value' => 'Full LOD 400 digital twins mapped to mechanical, electrical, and plumbing runs before ground breaking, eliminating costly on-site change orders.',
                'type' => 'textarea',
                'label' => 'Standard 1 Description',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_2_title',
                'value' => '02 / Real-Time Strut & Soil Telemetry',
                'type' => 'text',
                'label' => 'Standard 2 Title',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_2_desc',
                'value' => 'Automated strain gauges and vibrating-wire piezometers continuously monitoring earth pressure and deep foundation settlement in real time.',
                'type' => 'textarea',
                'label' => 'Standard 2 Description',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_3_title',
                'value' => '03 / 65+ MPa Continuous Batch QA',
                'type' => 'text',
                'label' => 'Standard 3 Title',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_3_desc',
                'value' => 'Mandatory 7-day, 14-day, and 28-day hydraulic compression crush tests on every structural pour, adhering strictly to ASTM C39 compliance.',
                'type' => 'textarea',
                'label' => 'Standard 3 Description',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_4_title',
                'value' => '04 / Transparent Lookahead Milestones',
                'type' => 'text',
                'label' => 'Standard 4 Title',
            ],
            [
                'page' => 'projects',
                'section' => 'standards',
                'key' => 'item_4_desc',
                'value' => 'Dedicated site superintendents providing 4-week lookahead stage schedules and live digital reporting portals for owners and developers.',
                'type' => 'textarea',
                'label' => 'Standard 4 Description',
            ],

            // 4.6 Projects CTA Banner
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'watermark',
                'value' => 'PARTNER',
                'type' => 'text',
                'label' => 'CTA Watermark',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'eyebrow',
                'value' => 'Tender & Preconstruction',
                'type' => 'text',
                'label' => 'CTA Eyebrow',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'title',
                'value' => 'Have an ambitious architectural or <br>commercial <span class="font-sketch font-bold text-[#f95716] normal-case text-[1.12em] tracking-normal inline-block transform -rotate-1">development</span> in mind?',
                'type' => 'textarea',
                'label' => 'CTA Title',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'description',
                'value' => 'Engage our senior preconstruction estimators and structural engineers for comprehensive constructability reviews, budget models, and tender packages.',
                'type' => 'textarea',
                'label' => 'CTA Description',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'btn_1_text',
                'value' => 'Request Project Tender',
                'type' => 'text',
                'label' => 'CTA Button 1 Text',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'btn_1_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'CTA Button 1 URL',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'btn_2_text',
                'value' => 'Schedule Technical Consultation',
                'type' => 'text',
                'label' => 'CTA Button 2 Text',
            ],
            [
                'page' => 'projects',
                'section' => 'cta',
                'key' => 'btn_2_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'CTA Button 2 URL',
            ],

            // ==========================================
            // 5. PROJECT DETAIL / CASE STUDY CONTENT
            // ==========================================
            [
                'page' => 'project_detail',
                'section' => 'narrative',
                'key' => 'watermark',
                'value' => 'ANALYSIS',
                'type' => 'text',
                'label' => 'Narrative Watermark Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'narrative',
                'key' => 'badge',
                'value' => 'Scope & Methodology',
                'type' => 'text',
                'label' => 'Narrative Section Badge',
            ],
            [
                'page' => 'project_detail',
                'section' => 'narrative',
                'key' => 'title',
                'value' => 'Architectural & Engineering Execution',
                'type' => 'text',
                'label' => 'Narrative Section Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'highlights',
                'key' => 'card_1_num',
                'value' => '01',
                'type' => 'text',
                'label' => 'Highlight Card 1 Number',
            ],
            [
                'page' => 'project_detail',
                'section' => 'highlights',
                'key' => 'card_1_title',
                'value' => 'Precision Structural Engineering',
                'type' => 'text',
                'label' => 'Highlight Card 1 Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'highlights',
                'key' => 'card_1_text',
                'value' => 'High-tensile reinforced concrete core with post-tensioned floor plates, engineered for zero-deflection structural performance under extreme seismic loads.',
                'type' => 'textarea',
                'label' => 'Highlight Card 1 Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'highlights',
                'key' => 'card_2_num',
                'value' => '02',
                'type' => 'text',
                'label' => 'Highlight Card 2 Number',
            ],
            [
                'page' => 'project_detail',
                'section' => 'highlights',
                'key' => 'card_2_title',
                'value' => 'Sustainable Material Integrity',
                'type' => 'text',
                'label' => 'Highlight Card 2 Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'highlights',
                'key' => 'card_2_text',
                'value' => '35% reduction in embodied carbon achieved through geopolymer slag mixes and recycled structural steel, certified for high durability environments.',
                'type' => 'textarea',
                'label' => 'Highlight Card 2 Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'sidebar',
                'key' => 'title',
                'value' => 'Technical Data Sheet',
                'type' => 'text',
                'label' => 'Sidebar Data Sheet Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'sidebar',
                'key' => 'btn_text',
                'value' => 'Inquire About Similar Scope',
                'type' => 'text',
                'label' => 'Sidebar Button Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'sidebar',
                'key' => 'btn_url',
                'value' => '#inquiry-cta',
                'type' => 'url',
                'label' => 'Sidebar Button URL',
            ],
            [
                'page' => 'project_detail',
                'section' => 'gallery',
                'key' => 'badge',
                'value' => 'Field Documentation',
                'type' => 'text',
                'label' => 'Gallery Section Badge',
            ],
            [
                'page' => 'project_detail',
                'section' => 'gallery',
                'key' => 'title',
                'value' => 'Site & Structural Gallery',
                'type' => 'text',
                'label' => 'Gallery Section Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'milestones',
                'key' => 'watermark',
                'value' => 'PHASES',
                'type' => 'text',
                'label' => 'Milestones Watermark Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'milestones',
                'key' => 'badge',
                'value' => 'Project Execution Progress',
                'type' => 'text',
                'label' => 'Milestones Section Badge',
            ],
            [
                'page' => 'project_detail',
                'section' => 'milestones',
                'key' => 'title',
                'value' => 'Chronological Milestones',
                'type' => 'text',
                'label' => 'Milestones Section Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'milestones',
                'key' => 'subtitle',
                'value' => 'Phased delivery schedule, QA validation gates, and certified structural completions.',
                'type' => 'textarea',
                'label' => 'Milestones Section Subtitle',
            ],
            [
                'page' => 'project_detail',
                'section' => 'cta',
                'key' => 'badge',
                'value' => 'Consultation & Tender Inquiries',
                'type' => 'text',
                'label' => 'Detail CTA Badge',
            ],
            [
                'page' => 'project_detail',
                'section' => 'cta',
                'key' => 'title',
                'value' => 'Planning A High-Tolerance Construction Project?',
                'type' => 'text',
                'label' => 'Detail CTA Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'cta',
                'key' => 'description',
                'value' => 'Connect with our civil engineering directors to review blueprints, structural calculations, and procurement schedules for your forthcoming development.',
                'type' => 'textarea',
                'label' => 'Detail CTA Description',
            ],
            [
                'page' => 'project_detail',
                'section' => 'cta',
                'key' => 'btn_1_text',
                'value' => 'Request Engineering Proposal',
                'type' => 'text',
                'label' => 'Detail CTA Button 1 Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'cta',
                'key' => 'btn_1_url',
                'value' => '#footer',
                'type' => 'url',
                'label' => 'Detail CTA Button 1 URL',
            ],
            [
                'page' => 'project_detail',
                'section' => 'cta',
                'key' => 'btn_2_text',
                'value' => 'Back to Portfolio',
                'type' => 'text',
                'label' => 'Detail CTA Button 2 Text',
            ],
            [
                'page' => 'project_detail',
                'section' => 'related',
                'key' => 'badge',
                'value' => 'Relevant Portfolio',
                'type' => 'text',
                'label' => 'Related Section Badge',
            ],
            [
                'page' => 'project_detail',
                'section' => 'related',
                'key' => 'title',
                'value' => 'Related Engineering Projects',
                'type' => 'text',
                'label' => 'Related Section Title',
            ],
            [
                'page' => 'project_detail',
                'section' => 'related',
                'key' => 'link_text',
                'value' => 'View Full Portfolio',
                'type' => 'text',
                'label' => 'Related Section Link Text',
            ],

            // ==========================================
            // 6. SEO & META TAGS
            // ==========================================
            [
                'page' => 'seo',
                'section' => 'meta',
                'key' => 'meta_title',
                'value' => 'Building & Co. - Civil Engineering & Premier Construction Enterprise',
                'type' => 'text',
                'label' => 'Global Meta Title',
            ],
            [
                'page' => 'seo',
                'section' => 'meta',
                'key' => 'meta_description',
                'value' => 'Leading commercial construction, structural engineering, geotechnical site management, and architectural excellence in urban development.',
                'type' => 'textarea',
                'label' => 'Global Meta Description',
            ],
            [
                'page' => 'seo',
                'section' => 'meta',
                'key' => 'meta_keywords',
                'value' => 'construction, civil engineering, structural engineering, commercial towers, building contractors, BIM modeling, infrastructure',
                'type' => 'text',
                'label' => 'Target SEO Keywords',
            ],
            [
                'page' => 'seo',
                'section' => 'og',
                'key' => 'og_title',
                'value' => 'Building & Co. - Engineering Landmark Structures',
                'type' => 'text',
                'label' => 'OpenGraph Social Title',
            ],
            [
                'page' => 'seo',
                'section' => 'og',
                'key' => 'og_description',
                'value' => 'Explore premier civil engineering, architectural mastery, and construction capabilities.',
                'type' => 'textarea',
                'label' => 'OpenGraph Social Description',
            ],
        ];

        foreach ($contents as $item) {
            WebsiteContent::updateOrCreate(
                [
                    'page' => $item['page'],
                    'section' => $item['section'],
                    'key' => $item['key'],
                ],
                [
                    'value' => $item['value'],
                    'type' => $item['type'],
                    'label' => $item['label'],
                ]
            );
        }

        WebsiteContent::clearPageCache();
    }
}
